-- ============================================================
-- GUARANTEE - Coverage Types per Product
-- DAS.be Backend - Legal Protection Insurance
-- ============================================================
-- Guarantees define what is covered by each product.
-- TELEBIB2 alignment: CoverageCode
-- DAS coverage types:
-- - Basic: Civil recovery, criminal defense, insurance contracts
-- - Extended: + Medical malpractice, neighborhood disputes
-- - Benefisc: + Family, tax, employment, succession, admin law
-- ============================================================

CREATE OR REPLACE TABLE GUARANTEE (
    -- Primary Key
    GUARANTEE_ID        DECIMAL(10, 0)  NOT NULL GENERATED ALWAYS AS IDENTITY,

    -- Foreign Key
    PRODUCT_ID          DECIMAL(10, 0)  NOT NULL,

    -- Guarantee Identification
    GUARANTEE_CODE      CHAR(10)        NOT NULL,       -- CoverageCode (TELEBIB2)
    GUARANTEE_NAME      VARCHAR(50)     NOT NULL,

    -- Coverage Details
    COVERAGE_LIMIT      DECIMAL(11, 2),                 -- Specific limit (null = product limit)
    WAITING_MONTHS      DECIMAL(2, 0),                  -- Specific waiting (null = product default)

    -- Status & Audit
    STATUS              CHAR(3)         DEFAULT 'ACT',  -- ACT/INA

    -- Constraints
    CONSTRAINT GUARANTEE_PK PRIMARY KEY (GUARANTEE_ID),
    CONSTRAINT GUARANTEE_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    CONSTRAINT GUARANTEE_STATUS_CK CHECK (STATUS IN ('ACT', 'INA'))
);

-- Indexes
CREATE INDEX GUARANTEE_PRODUCT_IX ON GUARANTEE (PRODUCT_ID);
CREATE INDEX GUARANTEE_CODE_IX ON GUARANTEE (GUARANTEE_CODE);
CREATE INDEX GUARANTEE_STATUS_IX ON GUARANTEE (STATUS);

-- Labels
LABEL ON TABLE GUARANTEE IS 'Coverage Types - DAS.be';
LABEL ON COLUMN GUARANTEE (
    GUARANTEE_ID    IS 'Guarantee ID',
    PRODUCT_ID      IS 'Product ID (FK)',
    GUARANTEE_CODE  IS 'Coverage Code (CoverageCode)',
    GUARANTEE_NAME  IS 'Coverage Name',
    COVERAGE_LIMIT  IS 'Specific Coverage Limit',
    WAITING_MONTHS  IS 'Specific Waiting Period',
    STATUS          IS 'Status (ACT/INA)'
);

-- ============================================================
-- Initial Guarantee Data
-- ============================================================

-- DAS Classic - Basic coverage
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'CIV_RECOV', 'Civil Recovery' FROM PRODUCT WHERE PRODUCT_CODE = 'CLASSIC';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'CRIM_DEF', 'Criminal Defense' FROM PRODUCT WHERE PRODUCT_CODE = 'CLASSIC';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'INS_CONTR', 'Insurance Contracts' FROM PRODUCT WHERE PRODUCT_CODE = 'CLASSIC';

-- DAS Connect - Extended coverage
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'CIV_RECOV', 'Civil Recovery' FROM PRODUCT WHERE PRODUCT_CODE = 'CONNECT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'CRIM_DEF', 'Criminal Defense' FROM PRODUCT WHERE PRODUCT_CODE = 'CONNECT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'INS_CONTR', 'Insurance Contracts' FROM PRODUCT WHERE PRODUCT_CODE = 'CONNECT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'MED_MALPR', 'Medical Malpractice' FROM PRODUCT WHERE PRODUCT_CODE = 'CONNECT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'NEIGHBOR', 'Neighborhood Disputes' FROM PRODUCT WHERE PRODUCT_CODE = 'CONNECT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'EMPLOY', 'Employment Law' FROM PRODUCT WHERE PRODUCT_CODE = 'CONNECT';

-- DAS Comfort - Full coverage
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'CIV_RECOV', 'Civil Recovery' FROM PRODUCT WHERE PRODUCT_CODE = 'COMFORT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'CRIM_DEF', 'Criminal Defense' FROM PRODUCT WHERE PRODUCT_CODE = 'COMFORT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'INS_CONTR', 'Insurance Contracts' FROM PRODUCT WHERE PRODUCT_CODE = 'COMFORT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'MED_MALPR', 'Medical Malpractice' FROM PRODUCT WHERE PRODUCT_CODE = 'COMFORT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'NEIGHBOR', 'Neighborhood Disputes' FROM PRODUCT WHERE PRODUCT_CODE = 'COMFORT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'EMPLOY', 'Employment Law' FROM PRODUCT WHERE PRODUCT_CODE = 'COMFORT';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'ADMIN', 'Administrative Law' FROM PRODUCT WHERE PRODUCT_CODE = 'COMFORT';

-- Conflits Benefisc - Maximum coverage with tax benefit
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'CIV_RECOV', 'Civil Recovery' FROM PRODUCT WHERE PRODUCT_CODE = 'CONFLIT_BF';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'CRIM_DEF', 'Criminal Defense' FROM PRODUCT WHERE PRODUCT_CODE = 'CONFLIT_BF';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'INS_CONTR', 'Insurance Contracts' FROM PRODUCT WHERE PRODUCT_CODE = 'CONFLIT_BF';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'MED_MALPR', 'Medical Malpractice' FROM PRODUCT WHERE PRODUCT_CODE = 'CONFLIT_BF';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'NEIGHBOR', 'Neighborhood Disputes' FROM PRODUCT WHERE PRODUCT_CODE = 'CONFLIT_BF';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'FAMILY', 'Family Law' FROM PRODUCT WHERE PRODUCT_CODE = 'CONFLIT_BF';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'TAX', 'Tax Law' FROM PRODUCT WHERE PRODUCT_CODE = 'CONFLIT_BF';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'EMPLOY', 'Employment Law' FROM PRODUCT WHERE PRODUCT_CODE = 'CONFLIT_BF';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'SUCCES', 'Succession Rights' FROM PRODUCT WHERE PRODUCT_CODE = 'CONFLIT_BF';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'ADMIN', 'Administrative Law' FROM PRODUCT WHERE PRODUCT_CODE = 'CONFLIT_BF';

-- FiscAssist - Tax-focused for businesses
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'TAX', 'Tax Law' FROM PRODUCT WHERE PRODUCT_CODE = 'FISCASST';
INSERT INTO GUARANTEE (PRODUCT_ID, GUARANTEE_CODE, GUARANTEE_NAME)
SELECT PRODUCT_ID, 'ADMIN', 'Administrative Law' FROM PRODUCT WHERE PRODUCT_CODE = 'FISCASST';
